version: '3.8'

services:
  cocktail-mixer:
    build: .
    container_name: cocktail-mixer
    ports:
      - "5000:5000"
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
